### PR TITLE
Update to 1.19.1

### PR DESCRIPTION
**Pull request by fantahund**
Update to 1.19.1

### CODE REVIEW

**Comment by kyrptonaught** [comment]
Thanks, looks like just 1 change was needed

**Comment by fantahund** [comment]
yes ^^

**Comment by cwshields** [comment]
I'm pretty new to all of this, but I tried building it myself and seemed to build successfully once, but I don't even know where to find the .jar mod file, and when I tried to build it again to test it, I got this error:

> A problem occurred configuring root project 'CMDKeybinds'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find net.kyrptonaught:kyrptconfig:1.4.14-1.19.1.
     Searched in the following locations:
       - file:/C:/development/CMDKeybinds/.gradle/loom-cache/remapped_mods/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
       - https://maven.fabricmc.net/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
       - https://libraries.minecraft.net/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
       - https://libraries.minecraft.net/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.jar
       - https://repo.maven.apache.org/maven2/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
       - file:/C:/Users/cwshi/.gradle/caches/fabric-loom/1.4.14-1.19.1/kyrptconfig.jar
       - file:/C:/development/CMDKeybinds/.gradle/loom-cache/1.4.14-1.19.1/kyrptconfig.jar
       - https://maven.kyrptonaught.dev/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
       - https://maven.shedaniel.me/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
       - https://maven.terraformersmc.com/releases/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
       - file:/C:/Users/cwshi/.m2/repository/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom

**Comment by yurseria** [comment]
> 



> I'm pretty new to all of this, but I tried building it myself and seemed to build successfully once, but I don't even know where to find the .jar mod file, and when I tried to build it again to test it, I got this error:
> 
> > A problem occurred configuring root project 'CMDKeybinds'.
> > Could not resolve all dependencies for configuration ':modImplementation'.
> > Could not find net.kyrptonaught:kyrptconfig:1.4.14-1.19.1.
> > Searched in the following locations:
> > - file:/C:/development/CMDKeybinds/.gradle/loom-cache/remapped_mods/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
> > - https://maven.fabricmc.net/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
> > - https://libraries.minecraft.net/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
> > - https://libraries.minecraft.net/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.jar
> > - https://repo.maven.apache.org/maven2/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
> > - file:/C:/Users/cwshi/.gradle/caches/fabric-loom/1.4.14-1.19.1/kyrptconfig.jar
> > - file:/C:/development/CMDKeybinds/.gradle/loom-cache/1.4.14-1.19.1/kyrptconfig.jar
> > - https://maven.kyrptonaught.dev/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
> > - https://maven.shedaniel.me/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
> > - https://maven.terraformersmc.com/releases/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom
> > - file:/C:/Users/cwshi/.m2/repository/net/kyrptonaught/kyrptconfig/1.4.14-1.19.1/kyrptconfig-1.4.14-1.19.1.pom

kyrptonaught:kyrptconfig is private library. so only owner can build it.

**Comment by fantahund** [comment]
https://jenkins.fantacs.de/job/CMDKeybinds/

**Comment by cwshields** [comment]
@fantahund Thanks! This is one of my favorite mods.

**Comment by kyrptonaught** [comment]
1.6.0-1.19.X was released with 1.19.1/1.19.2 support.

**Pull request merged**
