### PR TITLE
Added RepeatN

### PR DESCRIPTION
**Pull request by MeLlamoPeter**
Added an option that will benefit they gameplay in some servers. RepeatN spams the macro every "delay" time while holding, and keeps spaming it N times after releasing.

### CODE REVIEW

**Comment by kyrptonaught** [comment]
This looks good, thanks!

Before I go ahead and merge this and get this released I'd like to rework the raw config file saving and the config menu in mod menu. I'd like them to be more unique to each macro type. Now with the addition of this macro we have another value alongside delay that is not used by all macro types. I'd like to only have them shown when applicable.

Also I think the name repeatN isn't exactly self explanatory to what the macro, got any other ideas?

**Comment by MeLlamoPeter** [comment]
Maybe RepeatAfterRelease, since it spams while holding, and N times after

**Comment by kyrptonaught** [comment]
I did merge this and get it implemented into the 1.19 branch if you'd like to check it out. I modified the config so It now only shows the options if they are applicable to that config type

Just to clarify how this works, this macro should be executed n number of times regardless if you are holding the key or not?

**Comment by kyrptonaught** [comment]
1.6.0-1.19 was released with the RunNTimes macro type.

**Pull request merged**
