### PR TITLE
1.18

### PR DESCRIPTION
**Pull request by fantahund**
Update to 1.18 :>

### CODE REVIEW

**Comment by kyrptonaught** [comment]
Thank you for this! I'll take a look at it and get a release out shortly. 

I don't recall if I was fully finished and satisfied with the changes I made to the config screen just yet

**Comment by fantahund** [comment]
I can only tell you that it works. :D

**Comment by BloodDragon2580** [comment]
> I can only tell you that it works. :D

How can i build from this souce a Java file?

**Comment by fantahund** [comment]
> > I can only tell you that it works. :D
> 
> How can i build from this souce a Java file?

yes -> Clone my repository change to 1.18 an run ./gradlew build

**Comment by fantahund** [comment]
No unfortunately not but here you have the ready jar --> [https://github.com/fantahund/CMDKeybinds/releases/tag/Update](https://github.com/fantahund/CMDKeybinds/releases/tag/Update)

**Comment by kyrptonaught** [comment]
I released this on curseforge, thank you for the work!

**Comment by fantahund** [comment]
^^

**Pull request merged**
