### PR TITLE
Update to 1.19-pre3

### PR DESCRIPTION
**Pull request by fantahund**
Here the same. I don't know if you like it that much. But just need a 1.19 version of it :D

### CODE REVIEW

**Comment by fantahund** [comment]
Update 1.19 done ^^

**Comment by ghost** [comment]
Compilation of the mod was sucessful, however loading the mod into Minecraft 1.19 presents the following error:
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Command Macros' (cmdkeybind) 1.5.3-1.18 with any version that is compatible with:
		 - minecraft 1.19
Unmet dependency listing:
	 - Mod 'Command Macros' (cmdkeybind) 1.5.3-1.18 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
It appears as if the mod still thinks it's the 1.18 version.

```
                          ./+o+-       chip@tux-desktop
                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.15.0-33-generic
           .++ .:/++++++/-.+sss/`      Uptime: 2d 10h 39m
         .:++o:  /++++++++/:--:/-      Packages: 2390
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.1.16
       .:+o:+o/.          `+sssoo+/    Resolution: 3360x1848
  .++/+:+oo+o:`             /sssooo.   DE: Cinnamon 5.2.7
 /+++//+:`oo+o               /::--:.   WM: Muffin
 \+/+o+++`o++o               ++////.   WM Theme: Windows-10-Basic (Windows-10)
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Windows-10-Basic [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: mate
        \+.++o+o``-````.:ohdhhhhh+     Font: Sans 9
         `:o+++ `ohhhhhhhhyo++os:      Disk: 290G / 700G (43%)
           .o:`.syhhhhhhh/.oo++o`      CPU: Intel Xeon E5-2670 0 @ 16x 3.3GHz [37.0°C]
               /osyyyyyyo++ooo+++/     GPU: AMD Radeon RX 560 Series (polaris11, LLVM 13.0.1, DRM 3.42, 5.15.0-33-generic)
                   ````` +oo+++o\:     RAM: 11525MiB / 15984MiB
                          `oo++.      
```
```
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

**Comment by fantahund** [comment]
So 2 things. If you want to have the current version you have to build the 1.19 branch from my fork. You can not build this because you are missing a dependency to build this mod. But I can provide you a version here. [https://fantacs.de/cmdkeybind-1.5.2-1.19.jar](url)

**Comment by ghost** [comment]
I had clicked on your fork's branch and cloned it, but still no dice. Suppose not having the dependency would make sense since my gradle environment was just installed the other day (I'm not much of a java dev, ya see...). I'll go ahead and test out the version you provided.

**Comment by Mshangao** [comment]
Can I get link to 1.19 version of this mod, please? Link is not working from your comment is not working anymore :(

**Comment by fantahund** [comment]
Copy the link and Paste the link in your search line in your Browser.

**Comment by Mshangao** [comment]
Thanks man, it's working! :D

**Comment by kyrptonaught** [comment]
I have made and official release for 1.19 on the curseforge. Thanks for this!

**Pull request closed without merging**
